/**
 * @file Auto-generated TypeScript types from RescueGroups API field definitions
 * @generated 2025-11-11T00:06:18.200Z
 * DO NOT EDIT THIS FILE MANUALLY - regenerate with: node scripts/fetch-animal-fields.js
 */

// Total enum types: 77

/**
 * Animal species
 * API field: animalSpecies
 * Friendly name: Species
 * Note: Values manually defined (not provided by API)
 */
export type AnimalSpecies =
  | ''
  | 'Dog'
  | 'Cat'
  | 'Bird'
  | 'Rabbit'
  | 'Small Animal'
  | 'Horse'
  | 'Reptile'
  | 'Barnyard';

/**
 * Maps user-facing species names to lowercase API query values
 * Used when constructing search filters
 */
export const SPECIES_QUERY_MAP: Record<string, string> = {
  Dog: 'dog',
  Cat: 'cat',
  Bird: 'bird',
  Rabbit: 'rabbit',
  'Small Animal': 'smallanimal',
  Horse: 'horse',
  Reptile: 'reptile',
  Barnyard: 'barnyard',
} as const;

/**
 * Activity level
 * API field: animalActivityLevel
 */
export type ActivityLevel =
  | ''
  | 'Not Active'
  | 'Slightly Active'
  | 'Moderately Active'
  | 'Highly Active';

/**
 * Adoption pending
 * API field: animalAdoptionPending
 */
export type AdoptionPending = 'Yes' | 'No';

/**
 * Affectionate
 * API field: animalAffectionate
 */
export type Affectionate = '' | 'Yes';

/**
 * Altered
 * API field: animalAltered
 */
export type Altered = '' | 'No' | 'Yes';

/**
 * Apartment appropriate
 * API field: animalApartment
 */
export type Apartment = '' | 'Yes';

/**
 * Exact Birthdate
 * API field: animalBirthdateExact
 */
export type BirthdateExact = 'No' | 'Yes';

/**
 * Coat Length
 * API field: animalCoatLength
 */
export type CoatLength = '' | 'Short' | 'Medium' | 'Long';

/**
 * Courtesy
 * API field: animalCourtesy
 */
export type Courtesy = 'Yes' | 'No';

/**
 * Crate trained
 * API field: animalCratetrained
 */
export type Cratetrained = '' | 'Yes';

/**
 * Declawed
 * API field: animalDeclawed
 */
export type Declawed = '' | 'Yes' | 'No';

/**
 * Drools excessively
 * API field: animalDrools
 */
export type Drools = '' | 'Yes';

/**
 * Eager to please
 * API field: animalEagerToPlease
 */
export type EagerToPlease = '' | 'Yes';

/**
 * Ear type
 * API field: animalEarType
 */
export type EarType =
  | ''
  | 'Cropped'
  | 'Droopy'
  | 'Erect'
  | 'Long'
  | 'Missing'
  | 'Notched'
  | 'Rose'
  | 'Semi-erect'
  | 'Tipped'
  | 'Natural/Uncropped';

/**
 * Energy level
 * API field: animalEnergyLevel
 */
export type EnergyLevel = '' | 'Low' | 'Moderate' | 'High';

/**
 * Tries to escape
 * API field: animalEscapes
 */
export type Escapes = '' | 'Yes';

/**
 * Even-tempered
 * API field: animalEventempered
 */
export type Eventempered = '' | 'Yes';

/**
 * Exercise needs
 * API field: animalExerciseNeeds
 */
export type ExerciseNeeds = '' | 'Not Required' | 'Low' | 'Moderate' | 'High';

/**
 * Eye color
 * API field: animalEyeColor
 */
export type EyeColor =
  | ''
  | 'Black'
  | 'Blue'
  | 'Blue-brown'
  | 'Brown'
  | 'Copper'
  | 'Gold'
  | 'Gray'
  | 'Green'
  | 'Hazelnut'
  | 'Mixed'
  | 'Pink'
  | 'Yellow';

/**
 * Requires a home with fence
 * API field: animalFence
 */
export type Fence = '' | 'Not Required' | 'Any Type' | '3 foot' | '6 foot';

/**
 * Likes to fetch
 * API field: animalFetches
 */
export type Fetches = '' | 'Yes';

/**
 * Found
 * API field: animalFound
 */
export type Found = 'Yes' | 'No';

/**
 * General Age
 * API field: animalGeneralAge
 */
export type GeneralAge = '' | 'Baby' | 'Young' | 'Adult' | 'Senior';

/**
 * Size potential (general)
 * API field: animalGeneralSizePotential
 */
export type GeneralSizePotential =
  | ''
  | 'Small'
  | 'Medium'
  | 'Large'
  | 'X-Large';

/**
 * Gentle
 * API field: animalGentle
 */
export type Gentle = '' | 'Yes';

/**
 * Does well in a car
 * API field: animalGoodInCar
 */
export type GoodInCar = '' | 'Yes';

/**
 * Goofy
 * API field: animalGoofy
 */
export type Goofy = '' | 'Yes';

/**
 * Grooming needs
 * API field: animalGroomingNeeds
 */
export type GroomingNeeds = '' | 'Not Required' | 'Low' | 'Moderate' | 'High';

/**
 * Has allergies
 * API field: animalHasAllergies
 */
export type HasAllergies = '' | 'Yes';

/**
 * Hearing impaired
 * API field: animalHearingImpaired
 */
export type HearingImpaired = '' | 'Yes';

/**
 * Housetrained
 * API field: animalHousetrained
 */
export type Housetrained = '' | 'No' | 'Yes';

/**
 * Hypoallergenic
 * API field: animalHypoallergenic
 */
export type Hypoallergenic = '' | 'Yes';

/**
 * Independent / aloof
 * API field: animalIndependent
 */
export type Independent = '' | 'Yes';

/**
 * Indoor/Outdoor
 * API field: animalIndoorOutdoor
 */
export type IndoorOutdoor =
  | ''
  | 'Indoor Only'
  | 'Indoor and Outdoor'
  | 'Outdoor Only';

/**
 * Intelligent
 * API field: animalIntelligent
 */
export type Intelligent = '' | 'Yes';

/**
 * Euthanasia reason
 * API field: animalKillReason
 */
export type KillReason =
  | ''
  | 'Age'
  | 'Behavior'
  | 'Breed'
  | 'Medical'
  | 'Space';

/**
 * Lap pet
 * API field: animalLap
 */
export type Lap = '' | 'Yes';

/**
 * Leash trained
 * API field: animalLeashtrained
 */
export type Leashtrained = '' | 'Yes';

/**
 * Microchipped
 * API field: animalMicrochipped
 */
export type Microchipped = '' | 'Yes' | 'No';

/**
 * Mixed breed
 * API field: animalMixedBreed
 */
export type MixedBreed = '' | 'Yes' | 'No';

/**
 * Needs companion animal
 * API field: animalNeedsCompanionAnimal
 */
export type NeedsCompanionAnimal = '' | 'Yes';

/**
 * Needs a Foster
 * API field: animalNeedsFoster
 */
export type NeedsFoster = '' | 'Yes' | 'No';

/**
 * Reaction to new people
 * API field: animalNewPeople
 */
export type NewPeople =
  | ''
  | 'Cautious'
  | 'Friendly'
  | 'Protective'
  | 'Aggressive';

/**
 * Cold sensitive
 * API field: animalNoCold
 */
export type NoCold = '' | 'Yes';

/**
 * Not good with female dogs
 * API field: animalNoFemaleDogs
 */
export type NoFemaleDogs = '' | 'Yes';

/**
 * Heat sensitive
 * API field: animalNoHeat
 */
export type NoHeat = '' | 'Yes';

/**
 * Not good with large dogs
 * API field: animalNoLargeDogs
 */
export type NoLargeDogs = '' | 'Yes';

/**
 * Not good with male dogs
 * API field: animalNoMaleDogs
 */
export type NoMaleDogs = '' | 'Yes';

/**
 * Not good with small dogs
 * API field: animalNoSmallDogs
 */
export type NoSmallDogs = '' | 'Yes';

/**
 * Obedience training
 * API field: animalObedienceTraining
 */
export type ObedienceTraining =
  | ''
  | 'Needs Training'
  | 'Has Basic Training'
  | 'Well Trained';

/**
 * Obedient
 * API field: animalObedient
 */
export type Obedient = '' | 'Yes';

/**
 * Good for seniors / elderly
 * API field: animalOKForSeniors
 */
export type OKForSeniors = '' | 'Yes';

/**
 * Good with adults
 * API field: animalOKWithAdults
 */
export type OKWithAdults = '' | 'All' | 'Men Only' | 'Women Only';

/**
 * OK with cats
 * API field: animalOKWithCats
 */
export type OKWithCats = '' | 'Yes' | 'No';

/**
 * OK with dogs
 * API field: animalOKWithDogs
 */
export type OKWithDogs = '' | 'Yes' | 'No';

/**
 * Good with farm animals
 * API field: animalOKWithFarmAnimals
 */
export type OKWithFarmAnimals = '' | 'Yes';

/**
 * OK with kids
 * API field: animalOKWithKids
 */
export type OKWithKids = '' | 'Yes' | 'No';

/**
 * Older/ considerate kids only
 * API field: animalOlderKidsOnly
 */
export type OlderKidsOnly = '' | 'Yes';

/**
 * Needs ongoing medical care
 * API field: animalOngoingMedical
 */
export type OngoingMedical = '' | 'Yes';

/**
 * Owner experience needed
 * API field: animalOwnerExperience
 */
export type OwnerExperience = '' | 'None' | 'Species' | 'Breed';

/**
 * Playful
 * API field: animalPlayful
 */
export type Playful = '' | 'Yes';

/**
 * Likes toys
 * API field: animalPlaysToys
 */
export type PlaysToys = '' | 'Yes';

/**
 * Predatory
 * API field: animalPredatory
 */
export type Predatory = '' | 'Yes';

/**
 * Protective / territorial
 * API field: animalProtective
 */
export type Protective = '' | 'Yes';

/**
 * Sex
 * API field: animalSex
 */
export type Sex = '' | 'Female' | 'Male';

/**
 * Shedding amount
 * API field: animalShedding
 */
export type Shedding = '' | 'Moderate' | 'None' | 'High';

/**
 * Sight impaired
 * API field: animalSightImpaired
 */
export type SightImpaired = '' | 'Yes';

/**
 * Size unit of measure
 * API field: animalSizeUOM
 */
export type SizeUOM =
  | ''
  | 'Centimeters'
  | 'Hands'
  | 'Inches'
  | 'Kilograms'
  | 'Ounces'
  | 'Pounds';

/**
 * Skittish
 * API field: animalSkittish
 */
export type Skittish = '' | 'Yes';

/**
 * Special diet required
 * API field: animalSpecialDiet
 */
export type SpecialDiet = '' | 'Yes';

/**
 * Has special needs
 * API field: animalSpecialneeds
 */
export type Specialneeds = '' | 'No' | 'Yes';

/**
 * Allow sponsorship
 * API field: animalSponsorable
 */
export type Sponsorable = 'Yes' | 'No';

/**
 * Likes to swim
 * API field: animalSwims
 */
export type Swims = '' | 'Yes';

/**
 * Tail type
 * API field: animalTailType
 */
export type TailType =
  | ''
  | 'Bare'
  | 'Bob'
  | 'Curled'
  | 'Docked'
  | 'Kinked'
  | 'Long'
  | 'Missing'
  | 'Short';

/**
 * Timid / shy
 * API field: animalTimid
 */
export type Timid = '' | 'Yes';

/**
 * Up-to-date
 * API field: animalUptodate
 */
export type Uptodate = '' | 'Yes' | 'No';

/**
 * Likes to vocalize
 * API field: animalVocal
 */
export type Vocal = '' | 'Quiet' | 'Some' | 'Lots';

/**
 * Requires a Yard
 * API field: animalYardRequired
 */
export type YardRequired = '' | 'Yes' | 'No';
